version: '2.2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - lemmy
      - lettuce

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  lemmy:
    image: dessalines/lemmy:0.16.0
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"

      # for nginx-proxy configuration
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PATH=/api
      - HTTP_PORT=8536
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs

  lettuce:
    image: lettuce:dev
    ports:
      - "127.0.0.1:1235:3000"
    restart: always
    volumes:
      - ../lettuce/:/app
    environment:
      - NEXT_PUBLIC_LEMMY_SECURE=false
      - NEXT_PUBLIC_LEMMY_HOST=localhost

      # for nginx-proxy configuration
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PATH=/
    depends_on:
      - lemmy

  pictrs:
    image: asonix/pictrs:0.3.0-beta.12-r1
    ports:
      - "127.0.0.1:8537:8080"
      - "127.0.0.1:6670:6669"
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always

 
  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
