version: '2.2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - lemmy
      - lettuce

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  lemmy:
    image: dessalines/lemmy:0.16.0
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"

      # for nginx-proxy configuration
      - VIRTUAL_HOST=$host
      - VIRTUAL_PATH=/api
      - HTTP_PORT=8536
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs

  lettuce:
    image: lettuce:prod
    restart: always
    environment:
      # for nginx-proxy configuration
      - VIRTUAL_HOST=$host
      - VIRTUAL_PATH=/
    depends_on:
      - lemmy

  pictrs:
    image: asonix/pictrs:0.3.0-beta.12-r1
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always

  # todo: propper mail server
  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"

volumes:
  conf:
  vhost:
  html:
  certs:
  acme: