name: lettuce.link production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --build-arg host=lettuce.link --build-arg is_secure=true --file prod/Dockerfile -t lettuce:prod .
